export const dummy = [
  {
    item: "Charger",
    desc: "Warna putih",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "-",
  },
  {
    item: "Charger",
    desc: "Warna putih",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "-",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
  {
    item: "Hape",
    desc: "Udah retak",
    loc: "Auala An Naim",
    time: "05-05-23",
    by: "Agus",
    status: "Found",
    owner: "Andi 0876538712934",
  },
];
