export const dummy = [
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
  {
    room: "B 102",
    type: "Junior Suite",
    status: "Dirty",
    staff: "Agus",
    note: "Kaca kotor",
    reserv: "Check Out",
  },
];
